### ISSUE TITLE
getting info on a template but fails

### ISSUE THREAD

**Issue by mmeroberts** [privazio/pyone#3]
I am doing a simple "template = one.template.info(2)"

This is throwing the following:

Traceback (most recent call last):
  File "C:/Users/MartinRoberts/projects/pyNebula/nebuladriver/app.py", line 11, in <module>
    template = one.template.info (2)
  File "C:\Python27\lib\xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "C:\Python27\lib\site-packages\pyone\__init__.py", line 86, in _ServerProxy__request
    return self.__response(ret)
  File "C:\Python27\lib\site-packages\pyone\__init__.py", line 104, in __response
    return bindings.CreateFromDOM(nsDom.documentElement.childNodes[0])
  File "C:\Python27\lib\site-packages\pyone\bindings\__init__.py", line 76, in CreateFromDOM
    return pyxb.binding.basis.element.AnyCreateFromDOM(node, default_namespace)
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 1757, in AnyCreateFromDOM
    return cls.CreateDOMBinding(node, expanded_name.elementBinding(), _fallback_namespace=fallback_namespace)
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 1730, in CreateDOMBinding
    rv = type_class.Factory(_dom_node=node, **kw)
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 306, in Factory
    rv = cls._DynamicCreate(*args, **kw)
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 696, in _DynamicCreate
    return ctor(*args, **kw)
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 2133, in __init__
    self.extend(dom_node.childNodes[:], fallback_namespace)
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 2612, in extend
    [ self.append(_v, **kw) for _v in value_list ]
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 2515, in append
    value = element_binding._createFromDOM(node, expanded_name, _fallback_namespace=fallback_namespace)
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 1842, in _createFromDOM
    return element.CreateDOMBinding(node, self.elementForName(expanded_name), **kw)
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 1730, in CreateDOMBinding
    rv = type_class.Factory(_dom_node=node, **kw)
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 306, in Factory
    rv = cls._DynamicCreate(*args, **kw)
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 696, in _DynamicCreate
    return ctor(*args, **kw)
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 2133, in __init__
    self.extend(dom_node.childNodes[:], fallback_namespace)
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 2612, in extend
    [ self.append(_v, **kw) for _v in value_list ]
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 2515, in append
    value = element_binding._createFromDOM(node, expanded_name, _fallback_namespace=fallback_namespace)
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 1842, in _createFromDOM
    return element.CreateDOMBinding(node, self.elementForName(expanded_name), **kw)
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 1730, in CreateDOMBinding
    rv = type_class.Factory(_dom_node=node, **kw)
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 306, in Factory
    rv = cls._DynamicCreate(*args, **kw)
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 696, in _DynamicCreate
    return ctor(*args, **kw)
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 2133, in __init__
    self.extend(dom_node.childNodes[:], fallback_namespace)
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 2612, in extend
    [ self.append(_v, **kw) for _v in value_list ]
  File "C:\Python27\lib\site-packages\pyxb\binding\basis.py", line 2588, in append
    raise pyxb.MixedContentError(self, value, location)
pyxb.exceptions_.MixedContentError: Invalid non-element content

**Comment by rvalle** [comment]
Can you send me information about your environment? like a pip freeze.

looks like pyxb is struggling with the parse...

I wonder if the problem is related to the related to the parsing of this particular call, of if the problem is more general. Are all the other API calls also failing? Do you get anything else to work?

I will try to reproduce the problem, meanwhile.
